/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package whitworthian;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.naming.Context;
import javax.naming.InitialContext;
import javax.naming.NamingException;
import javax.sql.DataSource;
import javax.swing.DefaultListModel;
import javax.swing.JList;

/**
 *
 * @author ccolegrove17
 */
public class SearchPage extends javax.swing.JFrame {

    protected static ResultSet results;
    protected static int index;
    DatabaseConnection db = new DatabaseConnection();

    protected static boolean edit = false;
    //protected static DataSource dataSource;

    /**
     * Creates new form Interface
     */
    public SearchPage() throws NamingException {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchField = new javax.swing.JTextField();
        searchByBox = new javax.swing.JComboBox();
        resultsPage = new javax.swing.JScrollPane();
        resultList = new javax.swing.JList();
        searchButton = new javax.swing.JButton();
        searchLabel = new javax.swing.JLabel();
        modeLabel = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        employeeLoginMenuItem = new javax.swing.JMenuItem();
        logoutMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        addArticleMenuItem = new javax.swing.JMenuItem();
        addAuthorMenuItem = new javax.swing.JMenuItem();
        addPositionMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search page");
        setMinimumSize(new java.awt.Dimension(465, 300));

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });
        searchField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                searchFieldKeyPressed(evt);
            }
        });

        searchByBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Keyword", "Title", "Author", "Date (YYYY-MM-DD)", "Tag", "Category" }));

        resultList.setFixedCellHeight(20);
        resultList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resultListMouseClicked(evt);
            }
        });
        resultsPage.setViewportView(resultList);

        searchButton.setText("Search");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        searchLabel.setText("Search Terms:");

        modeLabel.setText("View Mode");

        jMenuBar1.setToolTipText("");

        fileMenu.setText("File");

        employeeLoginMenuItem.setText("Employee Login");
        employeeLoginMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeLoginMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(employeeLoginMenuItem);

        logoutMenuItem.setText("Logout");
        logoutMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(logoutMenuItem);

        jMenuBar1.add(fileMenu);

        editMenu.setText("Edit");

        addArticleMenuItem.setText("Add Article");
        addArticleMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addArticleMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(addArticleMenuItem);

        addAuthorMenuItem.setText("Add Author");
        addAuthorMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAuthorMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(addAuthorMenuItem);

        addPositionMenuItem.setText("Add Position");
        addPositionMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPositionMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(addPositionMenuItem);

        jMenuBar1.add(editMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addComponent(searchLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchByBox, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addGap(26, 26, 26))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(resultsPage)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(modeLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchByBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchButton)
                    .addComponent(searchLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultsPage, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(modeLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    /**
        This creates a new login window to prompt the user to login
        @param evt
        @return void
    */
    private void employeeLoginMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeLoginMenuItemActionPerformed
        try {
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            Login choose = new Login();
            // chooses where to create the new window
            choose.setLocation(dim.width / 2 - choose.getSize().width / 2, dim.height / 2 - choose.getSize().height / 2);
            choose.setVisible(true);
        } catch (Exception ex) {
            System.out.println("You're dumb" + ex.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_employeeLoginMenuItemActionPerformed

    /**
     * This opens a view frame for user to view the article
     * @param evt
     * @return void
    */
    private void resultListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resultListMouseClicked
        if (evt.getClickCount() == 2 && !evt.isConsumed()) {
            evt.consume();
            index = resultList.getSelectedIndex() + 1;
            //handle double click event.
            
            // checks to see if the user is add/edit or just viewing.
            if (edit) {
                try {

                    // creates an add/edit window for the user to edit or add the article
                    // This creates a window in a new thread so that when we insert all the words into the words table,
                    // the program will not hang and not be able to continue. 
                    
                    // Each time you instert all of the words into the words table, it takes about 30 seconds.
                    // This 30 seconds of accessing the database is moved a new thread.
                    java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                            AddEditArticle choose = new AddEditArticle();
                            try {
                                SearchPage.results.absolute(SearchPage.index);
                                choose.titleField.setText(SearchPage.results.getString(2));
                                choose.runWindow(results, index);
                                choose.setLocation(dim.width / 2 - choose.getSize().width / 2, dim.height / 2 - choose.getSize().height / 2);
                                choose.setVisible(true);
                            } catch (SQLException ex) {
                                Logger.getLogger(AddEditArticle.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    });

                } catch (Exception ex) {
                    System.out.println("You're dumb" + ex.getMessage());
                }
            } else {
                // open a view window for the article
                try {
                    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                    ViewArticle choose = new ViewArticle();
                    choose.runWindow(results, index);
                    choose.setLocation(dim.width / 2 - choose.getSize().width / 2, dim.height / 2 - choose.getSize().height / 2);
                    choose.setVisible(true);
                } catch (Exception ex) {
                    System.out.println("You're kinda dumb" + ex.getMessage());
                }
            }
        }
// TODO add your handling code here:
    }//GEN-LAST:event_resultListMouseClicked

    /**
     * If the user is logged in, there is a logout option that is populated in the file menu
     * Pressing this will log you out to where you will not be able to add/edit articles
     * @param evt 
     */
    private void logoutMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutMenuItemActionPerformed
        edit = false;
        logoutMenuItem.setVisible(false);
        addAuthorMenuItem.setVisible(false);
        addPositionMenuItem.setVisible(false);
        editMenu.setVisible(false);

        modeLabel.setText("View Mode");
        // TODO add your handling code here:
    }//GEN-LAST:event_logoutMenuItemActionPerformed

    /**
     * This will execute a query that will search for the input words
     * @param evt 
     */
    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        DefaultListModel listModel = new DefaultListModel();
        String searchBy = searchByBox.getSelectedItem().toString();
        String searchBox = searchField.getText();
        
        // cleans the input to defend agaisnt SQL injection
        searchBox = searchBox.replaceAll("[^a-zA-z0-9 \'\"]+", "");
        searchBox = searchBox.replace("\'", "\\\'");
        searchBox = searchBox.replace("\"", "\\\"");
        ResultSet rs = db.Search(searchBy, searchBox);
        System.out.println(searchBox);
        results = rs;
        
        // populates the jList with all of the search results
        try {
            while (rs.next() == true) {
                listModel.addElement("  " + rs.getString(2));
            }
            resultList.setModel(listModel);
            // TODO add your handling code here:
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_searchButtonActionPerformed

    /**
     * Executes SearchButtonActionPerformed when the "Enter" key is pressed.
     * @param evt 
     */
    private void searchFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchFieldKeyPressed
        if (evt.getKeyCode() == java.awt.event.KeyEvent.VK_ENTER) { //checks if the user presses enter in the text field
            searchButton.doClick();//clicks the button
        }    }//GEN-LAST:event_searchFieldKeyPressed

    /**
     * Allows the user to add an author and their contact information
     * @param evt 
     */
    private void addAuthorMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAuthorMenuItemActionPerformed
        try {
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            AddAuthor choose = new AddAuthor();
            choose.setLocation(dim.width / 2 - choose.getSize().width / 2, dim.height / 2 - choose.getSize().height / 2);
            choose.setVisible(true);
        } catch (Exception ex) {
            System.out.println("You're dumb" + ex.getMessage());
        }
    }//GEN-LAST:event_addAuthorMenuItemActionPerformed

    /**
     * Allows the user to add an employee position. This will then allow the add/edit article to 
     * query through the position table and populate the position drop down menu.
     * @param evt 
     */
    private void addPositionMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPositionMenuItemActionPerformed
        try {
            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
            AddPosition choose = new AddPosition();
            choose.setLocation(dim.width / 2 - choose.getSize().width / 2, dim.height / 2 - choose.getSize().height / 2);
            choose.setVisible(true);
        } catch (Exception ex) {
            System.out.println("You're dumb" + ex.getMessage());
        }
    }//GEN-LAST:event_addPositionMenuItemActionPerformed

    /**
     * The will open a blank article form for the user to fill in. This is on a separate thread
     * because of the time it takes to populate the database. We would like the user to continue
     * to use the program for the 30 seconds it takes to populate the database with the new words. 
     * @param evt 
     */
    private void addArticleMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addArticleMenuItemActionPerformed
        java.awt.EventQueue.invokeLater(new Runnable() {
                        public void run() {
                            Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                            AddEditArticle choose = new AddEditArticle();
                            try {
                                choose.addNewArticle();
                                choose.setLocation(dim.width / 2 - choose.getSize().width / 2, dim.height / 2 - choose.getSize().height / 2);
                                choose.setVisible(true);
                            } catch (Exception ex) {
                                Logger.getLogger(AddEditArticle.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    });

        // TODO add your handling code here:
    }//GEN-LAST:event_addArticleMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SearchPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                try {
                    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
                    SearchPage choose = new SearchPage();
                    choose.setLocation(dim.width / 2 - choose.getSize().width / 2, dim.height / 2 - choose.getSize().height / 2);
                    choose.setVisible(true);
                    logoutMenuItem.setVisible(false);
                    addAuthorMenuItem.setVisible(false);
                    addPositionMenuItem.setVisible(false);
                    editMenu.setVisible(false);
                } catch (Exception ex) {
                    System.out.println("You're really dumb" + ex.getMessage());
                }

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addArticleMenuItem;
    protected static javax.swing.JMenuItem addAuthorMenuItem;
    protected static javax.swing.JMenuItem addPositionMenuItem;
    protected static javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem employeeLoginMenuItem;
    private static javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar jMenuBar1;
    protected static javax.swing.JMenuItem logoutMenuItem;
    protected static javax.swing.JLabel modeLabel;
    private javax.swing.JList resultList;
    private javax.swing.JScrollPane resultsPage;
    protected static javax.swing.JButton searchButton;
    private javax.swing.JComboBox searchByBox;
    private javax.swing.JTextField searchField;
    private javax.swing.JLabel searchLabel;
    // End of variables declaration//GEN-END:variables
}
